server:
  port: 8085

spring:
  application:
    name: crackhash-manager

  mongodb:
    host: ${MONGO_DB_HOST:localhost}
    port: 27017
    database: crackhash_db_mongo
    username: mongo_user
    password: mongo_password
    authentication-database: admin
    representation:
      uuid: standard

send-type: ${SEND_TYPE:rest}

worker:
  number: ${WORKER_NUMBER:3}
  urls:
    - ${WORKER_URL_1:http://localhost:8086}
    - ${WORKER_URL_2:http://localhost:8086}
    - ${WORKER_URL_3:http://localhost:8086}

crack-hash:
  task:
    in_process_lifetime-duration-threshold: PT5S
    half_ready_lifetime-duration-threshold: PT10S

  kafka:
    producer:
      config:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        retries: 0
        acks: all
      topic: crackhash_task_request_topic
    consumer:
      config:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: crackhash_task_result_group_id
        auto-offset-reset: earliest
      topic: crackhash_task_result_topic