server:
  port: 8086

spring:
  application:
    name: crackhash-worker

  cloud:
    openfeign:
      client:
        config:
          managerFeignClient:
            url: ${MANAGER_URL:http://localhost:8085}

send-type: ${SEND_TYPE:rest}

crack-hash:
  cracking-hash-thread-pool-size: ${CRACKING_HASH_THREAD_POOL_SIZE:10}
  execution-timeout: ${CRACK_HASH_TASK_EXECUTION_TIMEOUT_MS:8000}
  send-progress-every-percent: ${SEND_PROGRESS_EVERY_PERCENT:5}

  kafka:
    producer:
      config:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        retries: 0
        acks: all
      topic: crackhash_task_result_topic

    consumer:
      config:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: crackhash_task_request_group_id
        auto-offset-reset: earliest
      properties:
        concurrency: ${WORKER_NUMBER:3}

      topic: crackhash_task_request_topic