version: '3.3'
services:
  crackhash_worker_service-1:
    build:
      dockerfile: Dockerfile
    container_name: "worker-service-1"
    environment:
      MANAGER_URL: http://crackhash_manager_service:8085
      SEND_TYPE: kafka
      WORKER_NUMBER: 2
    ports:
      - "8086:8086"

  crackhash_worker_service-2:
    build:
      dockerfile: Dockerfile
    container_name: "worker-service-2"
    environment:
      MANAGER_URL: http://crackhash_manager_service:8085
      SEND_TYPE: kafka
      WORKER_NUMBER: 2
    ports:
      - "8086:8087"