services:
  crackhash-worker-service-1:
    build:
      dockerfile: Dockerfile
    container_name: "worker-service-1"
    environment:
      KAFKA_URL: crackhash_kafka:9092
      MANAGER_URL: http://crackhash-manager-service:8085
      SEND_TYPE: rest
      WORKER_NUMBER: 1
    ports:
      - "8086:8086"
    networks:
      - crackhash-net
      -
networks:
  crackhash-net:
    name: "crackhash-net"
    driver: bridge
    external: true